include $(SRC_RT)/myOS/io/Makefile
include $(SRC_RT)/myOS/util/Makefile
include $(SRC_RT)/myOS/lib/Makefile

MYOS_OBJS =     output/myOS/start32.o \
			${IO_OBJS} \
			${UTIL_OBJS}

MYOS_INCLUDE = $(SRC_RT)/myOS/include
